---
name: Permissions
on:
  pull_request:
    paths:
      - ".github/workflows/permissions.yaml"

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Remove label
        run: gh pr edit "${PR:?}" --remove-label "blocked"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ github.event.number }}
